// ── Creative Portfolio Data ───────────────────────────────────────────────────
import { asset } from '../utils/asset'

export const services = [
  {
    icon: '🎬',
    title: 'Long-Form YouTube Editing',
    titleFr: 'Montage YouTube Long Format',
    desc: 'Engaging full-length videos with dynamic pacing, custom graphics, and storytelling techniques that keep audiences watching.',
    descFr: 'Vidéos longues et engageantes avec un rythme dynamique, des graphismes personnalisés et des techniques narratives qui captivent l\'audience.',
    color: '#FF4E8A',
  },
  {
    icon: '⚡',
    title: 'Short-Form Content',
    titleFr: 'Contenu Court Format',
    desc: 'High-retention TikToks, Reels, and Shorts engineered for viral potential with precision-cut edits and trending audio.',
    descFr: 'TikToks, Reels et Shorts à forte rétention conçus pour un potentiel viral, avec des montages précis et des musiques tendances.',
    color: '#4FACFE',
  },
  {
    icon: '📱',
    title: 'TikTok & Instagram Reels',
    titleFr: 'Reels TikTok & Instagram',
    desc: 'Platform-native vertical content with trendy effects, text animations, and hooks that maximize watch time and shares.',
    descFr: 'Contenu vertical natif aux plateformes avec effets tendances, animations de texte et accroches qui maximisent le temps de visionnage et les partages.',
    color: '#2B86C5',
  },
  {
    icon: '✨',
    title: 'Motion Graphics',
    titleFr: 'Motion Design',
    desc: 'Animated titles, lower thirds, transitions, and custom motion elements that elevate any video to a professional level.',
    descFr: 'Titres animés, bandeaux, transitions et éléments de motion personnalisés qui élèvent le niveau professionnel de toute vidéo.',
    color: '#7B6FF0',
  },
  {
    icon: '📣',
    title: 'Social Media Management',
    titleFr: 'Gestion des Réseaux Sociaux',
    desc: 'Full-service social strategy including content calendars, post scheduling, engagement, and analytics reporting.',
    descFr: 'Stratégie sociale complète incluant calendriers de contenu, planification des publications, engagement et rapports d\'analyse.',
    color: '#00E5A0',
  },
  {
    icon: '🎙️',
    title: 'Podcast Editing',
    titleFr: 'Montage de Podcast',
    desc: 'Professional audio cleanup, chapter markers, audiograms, and video podcast editing for a polished listener experience.',
    descFr: 'Nettoyage audio professionnel, marqueurs de chapitres, audiogrammes et montage vidéo de podcast pour une expérience d\'écoute soignée.',
    color: '#FF8C42',
  },
  {
    icon: '🏢',
    title: 'Business Videos',
    titleFr: 'Vidéos d\'Entreprise',
    desc: 'Corporate promos, product showcases, testimonials, and brand videos that convert viewers into customers.',
    descFr: 'Promos corporatives, présentations de produits, témoignages et vidéos de marque qui convertissent les spectateurs en clients.',
    color: '#4FACFE',
  },
  {
    icon: '📚',
    title: 'Educational Videos',
    titleFr: 'Vidéos Éducatives',
    desc: 'Screen recordings, explainer videos, and course content with engaging animations and crystal-clear narration.',
    descFr: 'Captures d\'écran, vidéos explicatives et contenu de cours avec des animations engageantes et une narration claire.',
    color: '#00E5A0',
  },
]

export const portfolioItems = [
  {
    id: 7,
    category: 'Vlog',
    title: 'Exploring China Part 2 — A Robot Knocked, I Opened the Door!',
    client: '[esc] with jonathan',
    description: 'Travel vlog edit for the "Exploring China" series — fast-paced storytelling, captions, and sound design built for daily-adventure pacing.',
    descriptionFr: 'Montage de vlog de voyage pour la série "Exploring China" — narration rythmée, sous-titres et design sonore pensés pour un rythme d\'aventure quotidienne.',
    results: 'Full edit · Captions · Sound design',
    resultsFr: 'Montage complet · Sous-titres · Design sonore',
    color: '#4FACFE',
    tags: ['Vlog', 'Travel', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=nThrXt8Stq8',
    thumbnail: 'https://i.ytimg.com/vi/nThrXt8Stq8/hqdefault.jpg',
  },
  {
    id: 8,
    category: 'Vlog',
    title: "Exploring China Part 3 — What's Inside Zootopia?",
    client: '[esc] with jonathan',
    description: 'Travel vlog edit covering a visit to a Disneyland-style park in China, with dynamic pacing and narrative-driven cuts.',
    descriptionFr: 'Montage de vlog de voyage couvrant une visite d\'un parc à thème en Chine, avec un rythme dynamique et un montage narratif.',
    results: 'Full edit · Captions · Sound design',
    resultsFr: 'Montage complet · Sous-titres · Design sonore',
    color: '#7B6FF0',
    tags: ['Vlog', 'Travel', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=igqzJakR7aQ',
    thumbnail: 'https://i.ytimg.com/vi/igqzJakR7aQ/hqdefault.jpg',
  },
  {
    id: 9,
    category: 'Vlog',
    title: 'Trying Bizarre Asian Snacks',
    titleFr: 'Testons des Snacks Asiatiques Insolites',
    client: 'SAMCH',
    description: 'Vlog edit for a Tunisian content creator tasting unusual Asian snacks, with comedic pacing, subtitles, and reaction cutaways.',
    descriptionFr: 'Montage de vlog pour un créateur de contenu tunisien goûtant des snacks asiatiques insolites, avec un rythme comique, des sous-titres et des inserts de réaction.',
    results: 'Full edit · Subtitles · Reaction cuts',
    resultsFr: 'Montage complet · Sous-titres · Réactions',
    color: '#FFB830',
    tags: ['Vlog', 'Food', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=2Pr9UET39TQ',
    thumbnail: 'https://i.ytimg.com/vi/2Pr9UET39TQ/hqdefault.jpg',
  },
  {
    id: 10,
    category: 'Vlog',
    title: 'Philippines B-Day Party of Tres Marias',
    client: 'Travel Vlog Client',
    clientFr: 'Client Vlog de Voyage',
    description: 'Travel vlog edit covering a birthday celebration in the Philippines, with highlight pacing and party-energy sound design.',
    descriptionFr: 'Montage de vlog de voyage couvrant une fête d\'anniversaire aux Philippines, avec un rythme dynamique et un design sonore festif.',
    results: 'Full edit · Highlight pacing · Audio mix',
    resultsFr: 'Montage complet · Rythme dynamique · Mixage audio',
    color: '#FF4E8A',
    tags: ['Vlog', 'Travel', 'YouTube'],
    link: 'https://youtu.be/pvadm5rrnhg',
    thumbnail: 'https://i.ytimg.com/vi/pvadm5rrnhg/hqdefault.jpg',
  },
  {
    id: 11,
    category: 'Educational',
    title: 'The First Thing Parents Miss When Cyberbullying Happens',
    client: 'Samantha Di Done',
    description: 'Vertical short-form edit on cyberbullying awareness for parents, with punchy captions and a hook-driven cut built for retention.',
    descriptionFr: 'Montage vertical court sur la sensibilisation des parents à la cyberintimidation, avec sous-titres percutants et accroche pensée pour la rétention.',
    results: 'Full edit · Captions · Vertical format',
    resultsFr: 'Montage complet · Sous-titres · Format vertical',
    color: '#00E5A0',
    tags: ['Educational', 'Shorts', 'YouTube'],
    link: 'https://www.youtube.com/shorts/lSR8rxnHaJw',
    thumbnail: 'https://i.ytimg.com/vi/lSR8rxnHaJw/hqdefault.jpg',
  },
  {
    id: 12,
    category: 'Educational',
    title: "L'intimidation peut devenir un crime",
    client: 'Samantha Di Done',
    description: 'French-language short on the legal consequences of bullying, edited for fast retention with on-screen text and clean pacing.',
    descriptionFr: 'Court métrage en français sur les conséquences légales de l\'intimidation, monté pour une rétention rapide avec texte à l\'écran et rythme soigné.',
    results: 'Full edit · Captions · Vertical format',
    resultsFr: 'Montage complet · Sous-titres · Format vertical',
    color: '#7B6FF0',
    tags: ['Educational', 'Shorts', 'YouTube'],
    link: 'https://www.youtube.com/shorts/xiy8Lp2mhtQ',
    thumbnail: 'https://i.ytimg.com/vi/xiy8Lp2mhtQ/hqdefault.jpg',
  },
  {
    id: 13,
    category: 'Educational',
    title: 'If You Were Bullied as a Kid… Comment What Helped You',
    client: 'Samantha Di Done',
    description: 'Emotional short-form edit inviting community engagement around childhood bullying experiences, paced for maximum watch-through.',
    descriptionFr: 'Montage court et émouvant invitant la communauté à échanger sur des expériences d\'intimidation vécues durant l\'enfance, rythmé pour maximiser le visionnage complet.',
    results: 'Full edit · Captions · Vertical format',
    resultsFr: 'Montage complet · Sous-titres · Format vertical',
    color: '#FFB830',
    tags: ['Educational', 'Shorts', 'YouTube'],
    link: 'https://www.youtube.com/shorts/TtmYYHvIKsQ',
    thumbnail: 'https://i.ytimg.com/vi/TtmYYHvIKsQ/hqdefault.jpg',
  },
  {
    id: 14,
    category: 'Educational',
    title: "As-tu vécu de l'intimidation? Écoute ça",
    client: 'Samantha Di Done',
    description: 'French-language awareness short on bullying experiences, edited with a strong opening hook and tight vertical pacing.',
    descriptionFr: 'Court métrage en français de sensibilisation aux expériences d\'intimidation, monté avec une accroche forte et un rythme vertical soigné.',
    results: 'Full edit · Captions · Vertical format',
    resultsFr: 'Montage complet · Sous-titres · Format vertical',
    color: '#FF4E8A',
    tags: ['Educational', 'Shorts', 'YouTube'],
    link: 'https://www.youtube.com/shorts/sD1F4JrA9GE',
    thumbnail: 'https://i.ytimg.com/vi/sD1F4JrA9GE/hqdefault.jpg',
  },
  {
    id: 15,
    category: 'Health',
    title: 'Health & Wellness Reel',
    titleFr: 'Reel Santé & Bien-être',
    client: 'Health Content Creator',
    clientFr: 'Créateur de Contenu Santé',
    description: 'Vertical short-form health content edited for retention, with punchy captions and hook-driven pacing.',
    descriptionFr: 'Contenu santé vertical au format court monté pour la rétention, avec sous-titres percutants et rythme basé sur l\'accroche.',
    results: 'Full edit · Captions · Vertical format',
    resultsFr: 'Montage complet · Sous-titres · Format vertical',
    color: '#00E5A0',
    tags: ['Health', 'Reels', 'Instagram'],
    link: 'https://www.instagram.com/reel/DJb-PJnshpF/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumbnail: asset('health/reel-1.jpg'),
  },
  {
    id: 16,
    category: 'Health',
    title: 'Health & Wellness Reel',
    titleFr: 'Reel Santé & Bien-être',
    client: 'Health Content Creator',
    clientFr: 'Créateur de Contenu Santé',
    description: 'Vertical short-form health content edited for retention, with punchy captions and hook-driven pacing.',
    descriptionFr: 'Contenu santé vertical au format court monté pour la rétention, avec sous-titres percutants et rythme basé sur l\'accroche.',
    results: 'Full edit · Captions · Vertical format',
    resultsFr: 'Montage complet · Sous-titres · Format vertical',
    color: '#4FACFE',
    tags: ['Health', 'Reels', 'Instagram'],
    link: 'https://www.instagram.com/reel/DI9LgxTMF-F/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumbnail: asset('health/reel-2.jpg'),
  },
  {
    id: 17,
    category: 'Health',
    title: 'Health & Wellness Reel',
    titleFr: 'Reel Santé & Bien-être',
    client: 'Health Content Creator',
    clientFr: 'Créateur de Contenu Santé',
    description: 'Vertical short-form health content edited for retention, with punchy captions and hook-driven pacing.',
    descriptionFr: 'Contenu santé vertical au format court monté pour la rétention, avec sous-titres percutants et rythme basé sur l\'accroche.',
    results: 'Full edit · Captions · Vertical format',
    resultsFr: 'Montage complet · Sous-titres · Format vertical',
    color: '#FFB830',
    tags: ['Health', 'Reels', 'Instagram'],
    link: 'https://www.instagram.com/reel/DIb3gUtMJXo/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumbnail: asset('health/reel-3.jpg'),
  },
  {
    id: 24,
    category: '3D Animation',
    title: '3D Animation',
    titleFr: 'Animation 3D',
    client: '3D Animation Project',
    clientFr: 'Projet d\'Animation 3D',
    description: 'A short 3D animation piece showcasing modeling, lighting, and motion design.',
    descriptionFr: 'Une courte pièce d\'animation 3D mettant en valeur la modélisation, l\'éclairage et le motion design.',
    results: '3D modeling · Lighting · Motion design',
    resultsFr: 'Modélisation 3D · Éclairage · Motion design',
    color: '#7B6FF0',
    tags: ['3D Animation', 'Motion Design'],
    link: 'https://youtu.be/aT1zwpsTqqo',
    thumbnail: 'https://i.ytimg.com/vi/aT1zwpsTqqo/hqdefault.jpg',
  },
  {
    id: 25,
    category: 'Business',
    title: 'Business Video Edit',
    titleFr: 'Montage Vidéo d\'Entreprise',
    client: 'Business Client',
    clientFr: 'Client Entreprise',
    description: 'Professional business video edit with clean pacing and polished visual storytelling.',
    descriptionFr: 'Montage vidéo professionnel pour entreprise avec un rythme soigné et une narration visuelle raffinée.',
    results: 'Full edit · Sound design · Color grade',
    resultsFr: 'Montage complet · Design sonore · Étalonnage',
    color: '#FFB830',
    tags: ['Business', 'YouTube'],
    link: 'https://youtu.be/YM-vnAGO1iQ?si=DkKYf4oDHiSyldLu',
    thumbnail: 'https://i.ytimg.com/vi/YM-vnAGO1iQ/hqdefault.jpg',
  },
  {
    id: 19,
    category: 'Documentary',
    title: 'Documentary Edit',
    titleFr: 'Montage de Documentaire',
    client: 'Documentary Project',
    clientFr: 'Projet Documentaire',
    description: 'Full documentary edit with narrative pacing, sound design, and color grading.',
    descriptionFr: 'Montage complet de documentaire avec rythme narratif, design sonore et étalonnage colorimétrique.',
    results: 'Full edit · Sound design · Color grade',
    resultsFr: 'Montage complet · Design sonore · Étalonnage',
    color: '#4FACFE',
    tags: ['Documentary', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=guN07PA13KY',
    thumbnail: 'https://i.ytimg.com/vi/guN07PA13KY/hqdefault.jpg',
  },
  {
    id: 20,
    category: 'Documentary',
    title: 'Documentary Edit',
    titleFr: 'Montage de Documentaire',
    client: 'Documentary Project',
    clientFr: 'Projet Documentaire',
    description: 'Full documentary edit with narrative pacing, sound design, and color grading.',
    descriptionFr: 'Montage complet de documentaire avec rythme narratif, design sonore et étalonnage colorimétrique.',
    results: 'Full edit · Sound design · Color grade',
    resultsFr: 'Montage complet · Design sonore · Étalonnage',
    color: '#7B6FF0',
    tags: ['Documentary', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=RvR7hEGclNI',
    thumbnail: 'https://i.ytimg.com/vi/RvR7hEGclNI/hqdefault.jpg',
  },
  {
    id: 21,
    category: 'Documentary',
    title: 'Documentary Edit',
    titleFr: 'Montage de Documentaire',
    client: 'Documentary Project',
    clientFr: 'Projet Documentaire',
    description: 'Full documentary edit with narrative pacing, sound design, and color grading.',
    descriptionFr: 'Montage complet de documentaire avec rythme narratif, design sonore et étalonnage colorimétrique.',
    results: 'Full edit · Sound design · Color grade',
    resultsFr: 'Montage complet · Design sonore · Étalonnage',
    color: '#FFB830',
    tags: ['Documentary', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=wbmBrIGdm-0',
    thumbnail: 'https://i.ytimg.com/vi/wbmBrIGdm-0/hqdefault.jpg',
  },
  {
    id: 22,
    category: 'Documentary',
    title: 'Documentary Edit',
    titleFr: 'Montage de Documentaire',
    client: 'Documentary Project',
    clientFr: 'Projet Documentaire',
    description: 'Full documentary edit with narrative pacing, sound design, and color grading.',
    descriptionFr: 'Montage complet de documentaire avec rythme narratif, design sonore et étalonnage colorimétrique.',
    results: 'Full edit · Sound design · Color grade',
    resultsFr: 'Montage complet · Design sonore · Étalonnage',
    color: '#00E5A0',
    tags: ['Documentary', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=tHj-DoR9IBE',
    thumbnail: 'https://i.ytimg.com/vi/tHj-DoR9IBE/hqdefault.jpg',
  },
  {
    id: 23,
    category: 'Documentary',
    title: 'Documentary Edit',
    titleFr: 'Montage de Documentaire',
    client: 'Documentary Project',
    clientFr: 'Projet Documentaire',
    description: 'Full documentary edit with narrative pacing, sound design, and color grading.',
    descriptionFr: 'Montage complet de documentaire avec rythme narratif, design sonore et étalonnage colorimétrique.',
    results: 'Full edit · Sound design · Color grade',
    resultsFr: 'Montage complet · Design sonore · Étalonnage',
    color: '#FF4E8A',
    tags: ['Documentary', 'YouTube'],
    link: 'https://www.youtube.com/watch?v=b3bIsilixrA',
    thumbnail: 'https://i.ytimg.com/vi/b3bIsilixrA/hqdefault.jpg',
  },
]

export const testimonials = [
  {
    name: 'Imad Doueihy',
    role: 'CEO',
    company: 'ClueCut',
    feedback: "Mohamed is a gem. You don't find someone like him very often. So if you have a chance to reach out to him, take it! I have been working with Mohamed for over 3 years now and he has never lacked or disappointed me. He's one of the key members of our agency and he is incredible! From punctuality and adaptability to speed and precision. He is unique and it's not an exaggeration. I really recommend him and I garantee success with him.",
    feedbackFr: "Mohamed est une perle rare. On ne trouve pas quelqu'un comme lui souvent. Si vous avez la chance de le contacter, saisissez-la ! Je travaille avec Mohamed depuis plus de 3 ans et il ne m'a jamais déçu. C'est l'un des membres clés de notre agence et il est incroyable ! De la ponctualité à l'adaptabilité, en passant par la rapidité et la précision. Il est unique, ce n'est pas une exagération. Je le recommande vivement et je garantis le succès avec lui.",
    rating: 5,
    color: '#2B86C5',
  },
  {
    name: 'Stacie Zaychuk',
    role: 'Content Creator',
    roleFr: 'Créatrice de Contenu',
    company: 'YouTube - 120K Subscribers',
    companyFr: 'YouTube - 120K Abonnés',
    feedback: "Mohamed delivered a strong edits that showed he really understands my storytelling style. He was communicative, reliable, and brought solid editing skills to the table. Excited to work with him on future videos!",
    feedbackFr: "Mohamed a livré des montages solides qui montrent qu'il comprend vraiment mon style narratif. Il était communicatif, fiable et a apporté de véritables compétences en montage. J'ai hâte de retravailler avec lui sur de prochaines vidéos !",
    rating: 5,
    color: '#FF3CAC',
  },
  {
    name: 'Jonathan Nguyen',
    role: 'Fitness Instructor',
    roleFr: 'Instructeur Fitness',
    company: 'Instagram - 28K Followers',
    companyFr: 'Instagram - 28K Abonnés',
    feedback: "Mohamed was amazing. He went above and beyond with what I asked for and was open to all my suggestions and ideas. His video editing on my videos helped get me more followers and engagement with social media, and I got to relax and not have to worry about editing.",
    feedbackFr: "Mohamed a été incroyable. Il est allé bien au-delà de ce que je demandais et est resté ouvert à toutes mes suggestions et idées. Son montage vidéo m'a aidé à gagner plus d'abonnés et d'engagement sur les réseaux sociaux, et j'ai pu me détendre sans me soucier du montage.",
    rating: 5,
    color: '#784BA0',
  },
  {
    name: 'Samantha Di Done',
    role: 'Lawyer',
    roleFr: 'Avocate',
    feedback: "Mohamed was professional, respectful, and a pleasure to work with throughout the entire project. He was kind, generous, and genuinely invested in helping the project succeed. Beyond delivering excellent work, he provided valuable advice, offered continuous support, and was always willing to go the extra mile whenever needed. I truly enjoyed working with him and would highly recommend him to anyone looking for a reliable and talented professional.",
    feedbackFr: "Mohamed a été professionnel, respectueux et un plaisir avec qui travailler tout au long du projet. Il était bienveillant, généreux et sincèrement investi dans la réussite du projet. Au-delà d'un excellent travail, il a apporté des conseils précieux, un soutien continu et s'est toujours montré prêt à aller plus loin en cas de besoin. J'ai vraiment apprécié travailler avec lui et je le recommande vivement à quiconque recherche un professionnel fiable et talentueux.",
    rating: 5,
    color: '#00E5A0',
  },
]

export const workflow = [
  {
    step: '01',
    title: 'Strategy Call',
    titleFr: 'Appel Stratégique',
    desc: 'We discuss your goals, audience, platform, and content direction to align on the vision.',
    descFr: 'Nous discutons de vos objectifs, votre audience, votre plateforme et la direction du contenu pour aligner la vision.',
    icon: '💡',
    color: '#4FACFE',
  },
  {
    step: '02',
    title: 'Raw Material',
    titleFr: 'Matériel Brut',
    desc: 'You share your footage, assets, brand kit, and any reference videos.',
    descFr: 'Vous partagez vos rushs, assets, kit de marque et toute vidéo de référence.',
    icon: '📁',
    color: '#7B6FF0',
  },
  {
    step: '03',
    title: 'Editing & Motion',
    titleFr: 'Montage & Motion',
    desc: 'Full editing session with motion graphics, color grading, audio mixing, and effects.',
    descFr: 'Session de montage complète avec motion design, étalonnage, mixage audio et effets.',
    icon: '✂️',
    color: '#FFB830',
  },
  {
    step: '04',
    title: 'Review Cycle',
    titleFr: 'Cycle de Révision',
    desc: 'You review the draft and provide feedback. Up to 2 revision rounds included.',
    descFr: 'Vous examinez le brouillon et donnez vos retours. Jusqu\'à 2 cycles de révision inclus.',
    icon: '🔁',
    color: '#00E5A0',
  },
  {
    step: '05',
    title: 'Final Delivery',
    titleFr: 'Livraison Finale',
    desc: 'Export in your required formats, optimized for each platform. Ready to publish.',
    descFr: 'Export dans les formats requis, optimisé pour chaque plateforme. Prêt à publier.',
    icon: '🚀',
    color: '#FF4E8A',
  },
]

export const stats = [
  { value: 8, suffix: '+', label: 'Projects Delivered', labelFr: 'Projets Livrés', icon: '📦', color: '#4FACFE' },
  { value: 3, suffix: '+', label: 'Years Experience', labelFr: 'Années d\'Expérience', icon: '⏳', color: '#7B6FF0' },
  { value: null, suffix: '', label: 'Top Rated on Upwork', labelFr: 'Top Rated sur Upwork', icon: '⭐', color: '#FFB830', badge: asset('top-rated.png') },
  { value: null, suffix: '', label: '100% Job Success on Upwork', labelFr: '100% de Réussite sur Upwork', icon: '🌍', color: '#00E5A0', badge: asset('success-jobs.png') },
]
